### ISSUE TITLE
:bento: 날씨 이미지 파일 추가

### ISSUE THREAD

**Issue by Juhwa-Lee1023** [UrrrrKWANG/Kloudy#108]
### 문제 상황
- 날씨 이미지 파일 추가

### TODO
- [x] 날씨 이미지 파일 추가

**Comment by Byeonjinha** [comment]
새로운 이미지 파일이 생겨서 추가한 뒤 클로즈 하겠습니다.

**Comment by Byeonjinha** [comment]
지수 이미지 파일이 생겨서 추가한 뒤 클로즈 하겠습니다.
