### ISSUE TITLE
🚑  cocoapods 오류

### ISSUE THREAD

**Issue by dkdo1406** [UrrrrKWANG/Kloudy#146]
### 문제 상황
- podfile의 버전만 적다보니 pods가 꼬여서 최신버전인데도 lottie-ios에서 오류 발생
- 현재 확인 중인 오류입니다. 
- 불편하시더라도 밑에 내용대로 임시로 수정해서 실행해주세요.
- 혹시 아래방법을 차례대로 했는데도 실행이 안되면 저에게 말해주세요.

### Pods 오류 해결 방법

Podfile.lock, Kloudy.xcworkspace, Pods 3개 파일을 삭제 후 pod install을 합니다.
- [ ] rm Podfile.lock
- [ ] rm -rf Kloudy.xcworkspace
- [ ] rm -rf Pods
- [ ] pod install
- [ ] 나중에 develop 브랜치에서 cocoapods 삭제 후 재설치 하기

**Comment by Juhwa-Lee1023** [comment]
감사합니다!!
