### ISSUE TITLE
:bug:  메모리 누수가 발생하고 있습니다.

### ISSUE THREAD

**Issue by 2youngjun** [UrrrrKWANG/Kloudy#267]
### 문제 상황
- 

### TODO
- [ ] 00하기

**Comment by Juhwa-Lee1023** [comment]
제가 처리하도록 하겠습니다!!!!
![image](https://user-images.githubusercontent.com/63584245/203303940-f33a7228-d57e-4dca-8654-546b5b6eeaf4.png)

**Comment by Byeonjinha** [comment]
섹시한 코인 좋아요
