### ISSUE TITLE
🐛  WeatherIndexView 의 우측 상단 CollectionView 가 표현되지 않고 있습니다.

### ISSUE THREAD

**Issue by 2youngjun** [UrrrrKWANG/Kloudy#315]
### 문제 상황
- WeatherIndexView 의 우측 상단 CollectionView 에 indexArray 가 전달되지 않고 있습니다.

### TODO
- [ ] WeatherIndexView 의 우측 상단 CollectionView 구현

**Comment by Byeonjinha** [comment]
내부지수 코드 정리하고 다시 닫도록 하겠습니다 👍
